import cypress from "cypress"
import '@testing-library/cypress/add-commands'

describe('loginformtest', () =>{
    it('user journey from character choice to register form to info display page', () => {
        cy.visit('http://localhost:3000/')
        cy.findByRole('img', {name: /empire_logo/i}).click()
        cy.wait(1000)
        cy.get('#root > div > div:nth-child(1) > div > div:nth-child(2) > div:nth-child(3)').click()
        cy.wait(1000)
        cy.get('#root > div > div:nth-child(1) > div > div:nth-child(2) > div:nth-child(3)').click()
        cy.wait(1000)
        cy.get('#root > div > div:nth-child(1) > div > div:nth-child(2) > div:nth-child(3)').click()
        cy.wait(1000)
        cy.findByRole('button', { name: /LOS/i}).click()
        cy.wait(1000)
        cy.get('[data-testid="Bossk"]')
        cy.get('#root > div > div > div:nth-child(3) > div > div > div').should('not.be.visible')
        cy.get('#root > div > div > div:nth-child(1) > div > div > div').should('not.be.visible')
        cy.get('input[placeholder*="Vorname"]').type('yannick')
        cy.findByRole('button', {  name: /Registrieren/i}).click()
        cy.findByText(/Vorname leer/i).should('not.exist')
        cy.findByText(/Nachname leer/i).should('exist')
        cy.wait(1000)
        cy.get('#root > div > div > div:nth-child(3) > div > div > div').should('be.visible')
        cy.get('#root > div > div > div:nth-child(1) > div > div > div').should('be.visible')
        cy.get('input[placeholder*="Nachname"]').type('Messinger')
        cy.get('input[placeholder*="Username"]').type('messi')
        cy.get('input[placeholder*="Geburtstag"]').type('2024-06-03')
        cy.get('input[placeholder*="Mailadresse"]').type('messi.de')
        cy.get('input[placeholder*="Telefonnummer"]').type('4567')
        cy.findByRole('button', {  name: /Registrieren/i}).click()
        cy.wait(1000)
        cy.findByText(/Vorname leer/i).should('not.exist')
        cy.findByText(/Nachname leer/i).should('not.exist')
        cy.findByText(/Username leer/i).should('not.exist')
        cy.findByText(/kein Geb. aus Zukunft/i).should('exist')
        cy.findByText(/Format: user@example.com/i).should('exist')
        cy.findByText(/nur Zahlen!/i).should('not.exist')
        cy.get('input[placeholder*="Geburtstag"]').type('1991-06-03')
        cy.get('input[placeholder*="Mailadresse"]').type('messi@web.de')
        cy.findByRole('button', {name: /Registrieren/i}).click()
        cy.get('#root > div > div > div:nth-child(3) > div > div > div').should('be.visible')
        cy.get('#root > div > div > div:nth-child(1) > div > div > div').should('be.visible')
        cy.wait(5000)
        cy.findByText(/Planet Info/i).should('exist')
        cy.findByText(/Charakter Info/i).should('exist')
        cy.findByText(/Schiff Info/i).should('exist')
        
        
    })
})