import cypress from "cypress"
import '@testing-library/cypress/add-commands'

describe('loginformtest', () =>{
    it('user journey from character choice to register form to info display page', () => {
        cy.visit('http://localhost:3000/')
        cy.findByRole('img', {name: /empire_logo/i}).click()
        cy.wait(1000)
        cy.get('#root > div > div:nth-child(1) > div > div:nth-child(2) > div:nth-child(3)').click()
        cy.wait(1000)
        cy.get('#root > div > div:nth-child(1) > div > div:nth-child(2) > div:nth-child(3)').click()
        cy.wait(1000)
        cy.get('#root > div > div:nth-child(1) > div > div:nth-child(2) > div:nth-child(3)').click()
        cy.wait(1000)
        cy.findByRole('button', { name: /go/i}).click()
        cy.wait(1000)
        cy.get('[data-testid="Bossk"]')
        cy.get('#root > div > div > div:nth-child(3) > div > div > div').should('not.be.visible')
        cy.get('#root > div > div > div:nth-child(1) > div > div > div').should('not.be.visible')
        cy.get('input[placeholder*="firstname"]').type('yannick')
        cy.findByRole('button', {  name: /register/i}).click()
        cy.findByText(/empty first name/i).should('not.exist')
        cy.findByText(/empty last name/i).should('exist')
        cy.wait(1000)
        cy.get('#root > div > div > div:nth-child(3) > div > div > div').should('be.visible')
        cy.get('#root > div > div > div:nth-child(1) > div > div > div').should('be.visible')
        cy.get('input[placeholder*="lastname"]').type('Messinger')
        cy.get('input[placeholder*="username"]').type('messi')
        cy.get('input[placeholder*="birthday"]').type('2024-06-03')
        cy.get('input[placeholder*="emailadress"]').type('messi.de')
        cy.get('input[placeholder*="phonenumber"]').type('4567')
        cy.findByRole('button', {  name: /register/i}).click()
        cy.wait(1000)
        cy.findByText(/empty first name/i).should('not.exist')
        cy.findByText(/empty last name/i).should('not.exist')
        cy.findByText(/empty username/i).should('not.exist')
        cy.findByText(/no birthday from future/i).should('exist')
        cy.findByText(/wrong mail format/i).should('exist')
        cy.findByText(/empty phone number/i).should('not.exist')
        cy.get('input[placeholder*="birthday"]').type('1991-06-03')
        cy.get('input[placeholder*="emailadress"]').type('messi@web.de')
        cy.findByRole('button', {name: /register/i}).click()
        cy.get('#root > div > div > div:nth-child(3) > div > div > div').should('be.visible')
        cy.get('#root > div > div > div:nth-child(1) > div > div > div').should('be.visible')
        cy.wait(5000)
        cy.findByText(/planet info/i).should('exist')
        cy.findByText(/character info/i).should('exist')
        cy.findByText(/ship info/i).should('exist')
        
        
    })
})